exercism/emacs-lisp

allergies/allergies-test.el
allergies/allergies.el
config.json

Heavily influenced/based on https://github.com/exercism/xlisp/tree/master/allergies

Add Allergies exercise

---

config.json
rna-transcription/example.el
rna-transcription/rna-transcription-test.el
rna-transcription/rna-transcription.el

Add exercise, make track active!

Rna transcription

---

docs/TESTS.org

Add more instructions for interactive tests

---

atbash-cipher/atbash-cipher-test.el
atbash-cipher/atbash-cipher.el
atbash-cipher/example.el
config.json

Based on the Common Lisp exercise at https://github.com/exercism/xlisp/tree/master/atbash-cipher
Example isn't the cleanest, but it works well.

Add atbash-cipher exercise

---

README.org

a step in fixing https://github.com/exercism/exercism.io/issues/3112.

move icon attribution from exercism.io/ATTRIBUTION.md here

---

config.json
exercises/etl/etl-test.el
exercises/etl/etl.el
exercises/etl/example.el

Let me know if there are any problems.

Added etl exercise.

---

config.json
exercises/word-count/example.el
exercises/word-count/word-count-test.el
exercises/word-count/word-count.el

Let me know if there are any problems.

Added word-count exercise.

---

docs/INSTALLATION.org

Fixes https://github.com/exercism/xelisp/issues/40

Fix URL to image in INSTALLATION.doc

---

grains/grains-test.el
grains/grains.el

Don't merge yet, still figuring out integer overflow issue.
Sending PR in hopes of suggestions on integer size problem.

WIP Add grains exercise.

---

config.json
exercises/phone-number/example.el
exercises/phone-number/phone-number-test.el
exercises/phone-number/phone-number.el

Let me know if there are any problems.

Added phone-number exercise.

---

.travis.yml
bin/test-examples

This should close #53, would be helpful if someone in could review my sloppy bash :smiling_imp:

Example testing

---

exercises/hamming/README.md
exercises/hamming/hamming-test.el
exercises/hamming/hamming.el

* Updates test suite for hamming to match tests from the problem-specifications
* Some spacing cleanup in the README for hamming
* requiring extra code in the implementation should be up to the user, so this
also removes `(require 'cl)` from the stub file

Update Hamming exercise

---

exercises/bob/README.md
exercises/bob/bob-test.el
exercises/bob/example.el

Update tests and example implementation for exercise `bob` and regenerate README
See #79

Update exercise bob to specification

---

exercises/hamming/hamming-test.el

Fix duplicate test name

---

config.json
exercises/crypto-square/README.md
exercises/crypto-square/crypto-square-test.el
exercises/crypto-square/crypto-square.el
exercises/crypto-square/example.el

Adapted from the Common Lisp track. I'm not 100% happy with my solution (I'd have preferred to either do string-only or buffer-only manipulation), but hey, maybe someone else will come up with a cooler one :)

Add crypto-square exercise

---

exercises/luhn/example.el
exercises/luhn/luhn-test.el

Updated luhn according to @xuchunyang 's suggestion in the pull request #108 thread

Updated luhn to use cl-lib instead of cl

---

docs/TESTS.md

I don't know what the standard URL format is that you use to link images, but here's a start.  I can refine as needed.
(Currently, the rendered page is broken.)

Fix image link

---

docs/LEARNING.md

Addresses https://github.com/exercism/exercism/issues/4804

Clarify location of non-bundled manuals

---

.travis.yml
exercises/bob/example.el

Mostly modernization and readability improvements, but a few functional improvements as well.
To be honest, the prior implementation looked a little intimidating. I'd like to make it more accessible. (The aref stuff especially is a little overboard.)

Some improvements to 'Bob' example implementation

---

docs/TESTS.md

Should fix #101.  I'm basing this patch on very old information, though, so please verify that this change will actually be effective :-)

Fix screenshot reference

---

exercises/hello-world/hello-world-test.el

Use proper string equality test for 'Hello, World'

---

exercises/.dir-locals.el
exercises/armstrong-numbers/example.el
exercises/difference-of-squares/example.el
exercises/luhn/example.el
exercises/raindrops/example.el
exercises/word-count/word-count-test.el

Sharp-quote is follow-up from [slack][1].  The rest is just boyscout stuff.
[1]: https://exercism-team.slack.com/archives/CASLG8D61/p1558667334002200

Improvements to style and to the Luhn exercise

---

exercises/hello-world/README.md

This was required to use the correct name for the function. Without this information only looking at the test file helps.

Add required function name to specification

---

exercises/practice/acronym/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/robot-name/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/trinary/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …

🤖 Sync exercise files keys based on file path patterns

---

exercises/practice/hello-world/hello-world.el

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

bin/stub-check

Fix CI tests

---

exercises/practice/word-count/.meta/config.json
exercises/practice/word-count/.meta/example.el
exercises/practice/word-count/.meta/tests.toml
exercises/practice/word-count/word-count-test.el

edit: I realized that the tests have to be based on https://github.com/exercism/problem-specifications, so I updated the PR.
closes #202

Add "with apostrophe" test to "Word Count" exercise

---

exercises/practice/acronym/acronym-test.el
exercises/practice/allergies/allergies-test.el
exercises/practice/anagram/anagram-test.el
exercises/practice/armstrong-numbers/armstrong-numbers-test.el
exercises/practice/atbash-cipher/atbash-cipher-test.el
exercises/practice/binary/binary-test.el
exercises/practice/bob/bob-test.el
exercises/practice/crypto-square/crypto-square-test.el
exercises/practice/difference-of-squares/difference-of-squares-test.el
exercises/practice/etl/etl-test.el
exercises/practice/gigasecond/gigasecond-test.el
exercises/practice/grains/grains-test.el
exercises/practice/hamming/hamming-test.el
exercises/practice/hello-world/hello-world-test.el
exercises/practice/leap/leap-test.el
exercises/practice/luhn/luhn-test.el
exercises/practice/nucleotide-count/nucleotide-count-test.el
exercises/practice/pangram/pangram-test.el
exercises/practice/perfect-numbers/perfect-numbers-test.el
exercises/practice/phone-number/phone-number-test.el
exercises/practice/raindrops/raindrops-test.el
exercises/practice/rna-transcription/rna-transcription-test.el
exercises/practice/robot-name/robot-name-test.el
exercises/practice/roman-numerals/roman-numerals-test.el
exercises/practice/run-length-encoding/run-length-encoding-test.el
exercises/practice/trinary/trinary-test.el
exercises/practice/two-fer/two-fer-test.el
exercises/practice/word-count/word-count-test.el

The file containing the exercise implementation didn't get loaded.
fixes #216

Fix: Exercise tests failing inside of the Docker container

---

exercises/practice/perfect-numbers/.meta/example.el

Before:
Ran 13 tests, 13 results as expected, 0 unexpected (2022-10-05 16:58:04+0200, 37.203005 sec)
After:
Ran 13 tests, 13 results as expected, 0 unexpected (2022-10-05 16:57:13+0200, 0.006244 sec)

Fix: Example implementation of perfect-numbers is slowing down CI

---

exercises/practice/leap/leap-test.el

Sync tests for 'leap' exercise with canonical tests

---

exercises/practice/acronym/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/trinary/.meta/config.json
exercises/practice/two-fer/.meta/config.json

This brings in recent improvements to the metadata for all practice exercises.

Sync metadata with problem-specifications

---

exercises/practice/acronym/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/list-ops/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/robot-name/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/trinary/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

Reformat exercise config files

---

config.json
exercises/practice/all-your-base/.docs/instructions.md
exercises/practice/all-your-base/.meta/config.json
exercises/practice/all-your-base/.meta/example.el
exercises/practice/all-your-base/.meta/tests.toml
exercises/practice/all-your-base/all-your-base-test.el
exercises/practice/all-your-base/all-your-base.el

See https://github.com/exercism/problem-specifications/issues/279

Deprecate binary exercise and replace with all-your-base

---

exercises/practice/phone-number/.meta/tests.toml
exercises/practice/phone-number/phone-number-test.el

Sync exercises

---

exercises/practice/nucleotide-count/.docs/hints.md
exercises/practice/nucleotide-count/.docs/instructions.md

With this PR, my goals are:
* Update the output example. I just realized this when reading the tests, that the expected output was an association list. In the beginning, I thought I would need to create some sort of string to match the example.
* Add some hints to help a novice in the Emacs Lisp world. I added the link to the Elisp characters, and association list documentation.
With this change, I believe that the instructions are more clear, and will help novices.
Let me know if you'd like me to change something in this branch.

Update instructions for nucleotide-count exercise

---

exercises/practice/etl/.docs/instructions.md
exercises/practice/etl/.docs/introduction.md
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/rna-transcription/.docs/introduction.md
exercises/practice/two-fer/.docs/instructions.md
exercises/practice/word-count/.docs/instructions.md
exercises/practice/word-count/.docs/introduction.md

Upstream: https://github.com/exercism/problem-specifications/
closes #279

Sync practice exercises with `problem-specifications` upstream

---

README.md

Takes influence from the READMEs of the Python, Common Lisp, and Javascript tracks.

Make README.md more inviting and informative

---

README.md

Test runner is on Emacs 28.2 now

Update Emacs version in README.md

---

exercises/practice/queen-attack/.meta/tests.toml

Add tests.toml for Queen Attack exercise (closes #313)

---

exercises/practice/pangram/pangram-test.el
exercises/practice/pangram/pangram.el

Related to #229. Tests are all there, but I did some formatting.

Sync pangram tests

---

exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/nucleotide-count/nucleotide-count-test.el
exercises/practice/nucleotide-count/nucleotide-count.el

Related to #229. All tests are present so I added the missing author from #45, swapped the expected and result order, and formatted the stub file.

Sync nucleotide-count tests

---

exercises/practice/raindrops/raindrops-test.el
exercises/practice/raindrops/raindrops.el

Sync raindrops tests

---

exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/anagram-test.el
exercises/practice/anagram/anagram.el

Related to #229. I left off the last two Unicode tests so we can decide later whether we want to handle them or not.

Sync anagram tests

---

exercises/practice/allergies/allergies-test.el
exercises/practice/allergies/allergies.el

Sync allergies tests

---

exercises/practice/acronym/.meta/example.el
exercises/practice/acronym/acronym-test.el
exercises/practice/acronym/acronym.el

Sync acronym tests

---

config.json
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/resistor-color-duo/.meta/config.json
exercises/practice/resistor-color-duo/.meta/example.el
exercises/practice/resistor-color-duo/.meta/tests.toml
exercises/practice/resistor-color-duo/resistor-color-duo-test.el
exercises/practice/resistor-color-duo/resistor-color-duo.el

@exercism/emacs-lisp, there's some noise in the track config because `configlet create --practice-exercise <slug>` now formats the track config.

Add resistor-color-duo exercise

---

exercises/practice/etl/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/word-count/.meta/config.json

Found some missing authors to populate.

Add missing authors to exercise configs

---

config.json
exercises/practice/eliuds-eggs/.docs/instructions.md
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/eliuds-eggs/.meta/config.json
exercises/practice/eliuds-eggs/.meta/example.el
exercises/practice/eliuds-eggs/.meta/tests.toml
exercises/practice/eliuds-eggs/eliuds-eggs-test.el
exercises/practice/eliuds-eggs/eliuds-eggs.el

Add eliud's eggs

---

config.json
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.meta/config.json
exercises/practice/resistor-color/.meta/example.el
exercises/practice/resistor-color/.meta/tests.toml
exercises/practice/resistor-color/resistor-color-test.el
exercises/practice/resistor-color/resistor-color.el

Add resistor-color

---

exercises/practice/hamming/hamming-test.el
exercises/practice/hamming/hamming.el

Sync hamming tests and update stub

---

exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/luhn.el

Sync tests for luhn and update stub

---

exercises/practice/bob/bob-test.el
exercises/practice/bob/bob.el

All tests are present but the inputs don't fully match the ones in the problem specifications.

Sync test inputs for bob

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.docs/introduction.md
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/example.el
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/dnd-character-test.el
exercises/practice/dnd-character/dnd-character.el

Add dnd-character

---

config.json
exercises/practice/robot-simulator/.docs/instructions.md
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/robot-simulator/.meta/example.el
exercises/practice/robot-simulator/.meta/tests.toml
exercises/practice/robot-simulator/robot-simulator-test.el
exercises/practice/robot-simulator/robot-simulator.el

Add robot simulator

---

config.json
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.docs/introduction.md
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/example.el
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/pig-latin-test.el
exercises/practice/pig-latin/pig-latin.el

This is my first time contributing. Let me know if anything is amiss.

add Pig Latin, part of 24 in 48

---

.github/workflows/ci.yml
README.md
exercises/practice/triangle/triangle-test.el

Corresponding PR to https://github.com/exercism/emacs-lisp-test-runner/pull/75

Upgrade CI test run to Emacs 29.3

---

.github/workflows/ci.yml
README.md

Also see https://github.com/exercism/emacs-lisp-test-runner/pull/77

Upgrade CI test run to Emacs 29.4

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/introduction.md
exercises/practice/zebra-puzzle/.docs/instructions.md
exercises/practice/zebra-puzzle/.docs/introduction.md
exercises/practice/zebra-puzzle/.meta/example.el

zebra-puzzle example solution updated with hobbies
[no important files changed]

Sync exercise docs

---

tools/practice-exercise-generator.el

fixes #431
@kmarker1101 Can you please have a look?

practice-exercise-generator: Remove alphanumeric chars except '-'

---

exercises/practice/hamming/.meta/config.json
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/sublist/.docs/instructions.md

Sync docs and metadata

---

exercises/practice/bob/.meta/tests.toml
exercises/practice/bob/bob-test.el
exercises/practice/hamming/.docs/instructions.md
exercises/practice/hamming/.docs/introduction.md
exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/pythagorean-triplet/.docs/instructions.md
exercises/practice/pythagorean-triplet/.docs/introduction.md
exercises/practice/pythagorean-triplet/.meta/config.json
exercises/practice/square-root/.docs/instructions.md
exercises/practice/square-root/.docs/introduction.md

Sync files, metadata, and tests

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.docs/introduction.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/grade-school/.docs/instructions.md
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/phone-number/.docs/introduction.md
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/pig-latin-test.el

Sync files

---

exercises/practice/anagram/.docs/instructions.md
exercises/practice/grains/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.docs/introduction.md
exercises/practice/pascals-triangle/.docs/introduction.md
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/say/.meta/config.json

Sync exercise instructions

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/grains/.docs/instructions.md
exercises/practice/grains/.docs/introduction.md
exercises/practice/sieve/.docs/instructions.md
exercises/practice/simple-cipher/.docs/instructions.md

Sync instructions

---

.github/workflows/ci.yml

See https://github.com/exercism/emacs-lisp-test-runner/pull/83

Upgrade CI workflow to Emacs 30.1

---

exercises/practice/resistor-color-trio/.docs/instructions.append.md
exercises/practice/resistor-color-trio/.meta/example.el
exercises/practice/resistor-color-trio/resistor-color-trio-test.el

We add test cases for
- 3.3 kiloohms
- 3.3 megaohms
- 990 megaohms
- 9.9 gigaohms

resistor-color-trio: decimal test cases

---

exercises/practice/simple-cipher/.docs/instructions.md
exercises/practice/simple-cipher/.meta/config.json

resolves #482
[no important files changed]

Sync simple-cipher exercise
