exercism/emacs-lisp

SETUP.org

Remove the reference to the deprecated [help.exercism.io](http://help.exercism.io) and point to [exercism.io/languages](http://exercism.io/languages/elisp) instead.
Fixes #32.

Deprecate help.exercism.io

---

config.json
exercises/roman-numerals/example.el
exercises/roman-numerals/roman-numerals-test.el
exercises/roman-numerals/roman-numerals.el

Let me know if there are any problems!

Added roman-numerals exercise.

---

config.json
exercises/nucleotide-count/example.el
exercises/nucleotide-count/nucleotide-count-test.el
exercises/nucleotide-count/nucleotide-count.el

Let me know if there are any problems.

Added nucleotide-count exercise.

---

docs/LEARNING.org

Link to http://decomplecting.org/blog/2014/10/23/welcome-to-the-dark-side-switching-to-emacs/ is inaccessible to me. This change is about to remove it from this document. But it is just changed or going to be available soon, let me know and I will update it.
/cc @yurrriq

Remove missing learning resources

---

exercises/grains/grains-test.el

The test is currently using `equal` which is less than ideal for numbers as it forbids differing types (such as integers and floats).  The thing is that elisp doesn't support bignums in the first place, so anything bigger than `max-positive-fixnum` overflows in a float.  A user anticipating this and using floats for everything will therefore run into the problem that this makes more than half of the tests fail as they use integers.

Use = for comparing numbers

---

exercises/word-count/word-count-test.el

The test code defines an `equal-assoc` helper, but didn't make use of it.  Without it the tests can only succeed if the alist has been constructed in reverse order.

Use equal-assoc helper to not depend on order

---

exercises/robot-name/robot-name-test.el

No need for (require 'cl) when we have regex...

Simplify name test

---

config/exercise_readme.go.tmpl
exercises/allergies/README.md
exercises/anagram/README.md
exercises/atbash-cipher/README.md
exercises/binary/README.md
exercises/bob/README.md
exercises/difference-of-squares/README.md
exercises/etl/README.md
exercises/gigasecond/README.md
exercises/grains/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/nucleotide-count/README.md
exercises/perfect-numbers/README.md
exercises/phone-number/README.md
exercises/raindrops/README.md
exercises/rna-transcription/README.md
exercises/robot-name/README.md
exercises/roman-numerals/README.md
exercises/word-count/README.md

We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …

Generate static exercise README templates

---

exercises/two-fer/two-fer.el

I realized that the `two-fer.el` were using the same code template as `hello-world.el`. I updated it.

Fix two-fer exercise commentary

---

exercises/difference-of-squares/difference-of-squares-test.el
exercises/difference-of-squares/example.el

In exercise "difference-of-squares", renamed `square-of-sums` to `square-of-sum`, and `difference-of-sums` to `difference-of-squares`.

difference-of-squares: renamed square-of-sums to square-of-sum

---

exercises/two-fer/two-fer-test.el

Use `string=` instead of `equal` in Two-Fer tests

---

exercises/word-count/example.el

Mostly readability/accessibility, but also note usage of `assoc-string` instead of `assoc` to set a good example.

Word count example implementation improvements

---

exercises/acronym/acronym.el
exercises/acronym/example.el
exercises/allergies/example.el
exercises/anagram/anagram.el
exercises/anagram/example.el
exercises/armstrong-numbers/example.el
exercises/atbash-cipher/atbash-cipher-test.el
exercises/atbash-cipher/example.el
exercises/crypto-square/example.el
exercises/difference-of-squares/example.el
exercises/etl/etl-test.el
exercises/grains/example.el
exercises/hamming/example.el
exercises/perfect-numbers/example.el
exercises/raindrops/example.el
exercises/raindrops/raindrops.el
exercises/rna-transcription/example.el
exercises/rna-transcription/rna-transcription-test.el
exercises/roman-numerals/example.el

Set a good example!  Feature 'cl has been deprecated for some time.
https://emacs.stackexchange.com/a/48115/2264

Require `cl-lib` instead of `cl`

---

exercises/word-count/word-count-test.el

`sort` is a destructive function, so it should not be passed quoted
values like those used in the tests.  Otherwise, the second time the
tests are run, they will compare against corrupted values.

Let word-count tests run multiple times correctly

---

.travis.yml
bin/stub-check

fixes #124
---
I wrote a bash script to verify that all exercises have a stub present in their directory.
I can include tests to verify it's behavior too if that is desired.
---
1. Run the script from a directory other than `elisp`, ie. the repo root.
2. Make an empty directory in `elisp/exercises` and then run the script to watch it catch the problem.
---
Also you can see how the output looks in the travis logs

Stub check

---

exercises/perfect-numbers/example.el
exercises/perfect-numbers/perfect-numbers-test.el
exercises/perfect-numbers/perfect-numbers.el

The tests for this exercise had severely deviated from the problem specification:
[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/perfect-numbers/canonical-data.json)
Unfortunately the large number tests take some time, but the range built off of the square root in the previous example did not yield a complete list of factors.  It could be worth it to find a more efficient method for getting the factors of a given number, but for now this at least gets the exercise up to spec.

Perfect Numbers: update exercise

---

exercises/leap/leap.el

According to tests the expected function should be named `leap-year-p`.

change leap to leap-year-p

---

bin/stub-check
docs/INSTALLATION.md
docs/TESTS.md
exercises/roman-numerals/roman-numerals-test.el

A couple of things in this PR:
- few broken links (org-mode style instead of markdown)
- fix a screenshot link. There were already attempts to fix it in #111 and #116. See the bottom of [this](https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md) document for the right format
- and the last is about a test in roman-numerals. I'm not sure if there are any specific rules for this, but I find it more convenient to have separate test for each case

Roman numerals separate tests

---

exercises/practice/acronym/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/robot-name/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/trinary/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

Each Concept and Practice Exercise will have to define a _blurb_, which is a short description of the exercise.
The blurb will be displayed on a track's exercises page and on exercise tooltips. For example:
Blurbs must be limited to 350 chars and will be truncated in some views.
For Practice Exercises that are based on an exercise defined in the problem-specification repo, the blurb must match the contents of the problem-specifications exercises, which is defined in its `metadata.yml` file. In this PR, we'll do an initial syncing of the blurb. The new [configlet](https://github.com/exercism/configlet) version will add support for doing this syncing automatically.
If the Practice Exercise was _not_ based on a problems-specifications exercise, we've used the blurb from its …

🤖 Add blurb to .meta/config.json files

---

SETUP.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/TESTS.md

We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17

[v3] Update Markdown files to latest spec

---

exercises/practice/acronym/.meta/tests.toml
exercises/practice/allergies/.meta/tests.toml
exercises/practice/anagram/.meta/tests.toml
exercises/practice/armstrong-numbers/.meta/tests.toml
exercises/practice/atbash-cipher/.meta/tests.toml
exercises/practice/binary/.meta/tests.toml
exercises/practice/bob/.meta/tests.toml
exercises/practice/crypto-square/.meta/tests.toml
exercises/practice/difference-of-squares/.meta/tests.toml
exercises/practice/etl/.meta/tests.toml
exercises/practice/gigasecond/.meta/tests.toml
exercises/practice/grains/.meta/tests.toml
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hello-world/.meta/tests.toml
exercises/practice/leap/.meta/tests.toml
exercises/practice/luhn/.meta/tests.toml
exercises/practice/nucleotide-count/.meta/tests.toml
exercises/practice/pangram/.meta/tests.toml
exercises/practice/perfect-numbers/.meta/tests.toml
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/raindrops/.meta/tests.toml
exercises/practice/rna-transcription/.meta/tests.toml
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/run-length-encoding/.meta/tests.toml
exercises/practice/trinary/.meta/tests.toml
exercises/practice/two-fer/.meta/tests.toml
exercises/practice/word-count/.meta/tests.toml

We're in the process of re-opening the [Problem Specifications repo](https://github.com/exercism/problem-specifications), as discussed in [this issue](https://github.com/exercism/problem-specifications/issues/1674).
This PR adds `.meta/tests.toml` files for all exercises for which canonical data is defined in the Problem Specifications repo.
We'll now discuss _why_ we're making this change.
While most of the changes to the Problem Specifications repo are specific to that repo, there is one track-specific change:
> If a track implements an exercise for which test data exists, the exercise _must_ contain a `.meta/tests.toml` file.
The goal of the `tests.toml` file is to keep track of which tests are implemented by the exercise.
Tests in this file are identified by their UUID and each test …

Bringing your track in line with the latest changes to Problem Specifications

---

exercises/practice/acronym/.meta/config.json
exercises/practice/allergies/.meta/config.json
exercises/practice/anagram/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/bob/.meta/config.json
exercises/practice/crypto-square/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/etl/.meta/config.json
exercises/practice/gigasecond/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/luhn/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/robot-name/.meta/config.json
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/trinary/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/word-count/.meta/config.json

_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_
---
With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).
Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.
These are the things you, the maintainers, should do:
**For clarity, authors should …

🤖 Add authors and contributors to Practice Exercises

---

README.md

- link to up to date contributing guide
- update repository link to link to current repository name

Update old and deprecated links in the README

---

exercises/practice/perfect-numbers/perfect-numbers-test.el

This test states that it tests the case where the number is `0`, yet `-1` is passed to the `classify` function.

Perfect Numbers: Fix "zero" test case

---

exercises/practice/leap/leap-test.el

This test was identical to the one above. Based on the test name, I
think that the year tested should be even.

Include an even year in tests

---

bin/test-examples

-
https://github.com/exercism/emacs-lisp/blob/8848da5d17e639f61bb9840fd55d12ee5b1873f3/.github/workflows/ci.yml
didn't exit with an error code if exercise tests where failing
- This was noticed because the tests for https://github.com/exercism/emacs-lisp/pull/210 did fail but the bash script didn't register the failure.

Fix: GHA ci.yml doesn't fail if exercise tests are failing

---

.github/workflows/ci.yml

CI runner in this repository should match runner in production.
See https://github.com/exercism/emacs-lisp-test-runner/commit/74b026194a2a9ca34c84dc3a1030293971e71442

Upgrade Emacs version to 28.1

---

.github/workflows/ci.yml

purcell/setup-emacs uses cached binaries through cachix (nix).
---
This speeds up the test run by about 1min 20sec or by about 70%.

Use purcell/setup-emacs to speed up CI

---

docs/INSTALLATION.md

- only mention versions in one place, where it is relevant (exercise target version), goes out of date too quickly
- recommend snap for Ubuntu as it is more up-to-date
- update Windows installation instructions to include installer
- add more links

Update Emacs installation instructions

---

docs/TESTS.md
exercises/shared/.docs/tests.md

- sync information between test doc files
- tell people to run `eval-buffer` in `TESTS.md`
- tell people that they have to reload the test file after making changes
- add Emacs Lisp function that reloads changes and only runs tests from the current buffer
- use `/usr/bin/env` in bash script for better portability
closes #205

Improve documentation of how to run tests

---

docs/TESTS.md

I looked at [how other tracks are linking to images in their docs](https://github.com/exercism/pharo-smalltalk/search?l=Markdown&q=png) and it seems like linking to GitHub
is the way to got.
fixes #175

Fix missing image in test documentation

---

docs/LEARNING.md

- split up into different sections, accommodate people just starting out with Emacs a bit more
- add installation instructions for starter kits
- add Doom Emacs starter kit for people switching from vim
- reference style guide and coding conventions
closes #198
works on #18 (https://github.com/exercism/emacs-lisp/issues/18#issuecomment-125612531)

Improve "Learning Emacs Lisp" doc

---

config.json
exercises/practice/list-ops/.docs/hints.md
exercises/practice/list-ops/.docs/instructions.append.md
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/list-ops/.meta/config.json
exercises/practice/list-ops/.meta/example.el
exercises/practice/list-ops/.meta/tests.toml
exercises/practice/list-ops/list-ops-test.el
exercises/practice/list-ops/list-ops.el

- as noted in the problem-specification that some tracks would do that, I added a namespace to avoid conflicts with existing functions (since users will often evaluate function definitions inside of emacs they would otherwise overwrite built-in functions in their running environment)
- I've added two additional functions:
- `list-sum`: this is just to drive the point home that you can implement functions like that very easily through the primitives implemented in this exercise
- `list-empty-p`: I hope to bring people towards the realization that nil = empty list in Emacs Lisp, checking if the `car` and `cdr` of a list are nil will not work.
Regarding `list-empty-p` we had this discussion on slack: https://app.slack.com/client/TAN6QMALR/CAQP7JL3T/thread/CAQP7JL3T-1665705236.652139
I think …

Add list ops exercise

---

docs/INSTALLATION.md
docs/RESOURCES.md
exercises/shared/.docs/help.md

The Exerism Forum (https://forum.exercism.org/) has now made Gitter redundant.
We're directing everyone there.

Remove reference to Gitter

---

exercises/practice/list-ops/list-ops-test.el

I saw that sometimes tracks include commented out bonus tests. I thought this was a nice opportunity to add bonus tests for people who want an extra challenge.

Add bonus tests to list-ops that break non-tco recursive solutions

---

docs/RESOURCES.md
exercises/shared/.docs/help.md

- recommend libera.chat instead of freenode
- reference Matrix channels
- add Emacs StackExchange to the shared exercise docs
- also recommend StackOverflow and StackExchange in the online docs

Update help resources

---

exercises/practice/list-ops/list-ops-test.el

If there is a duplicate test present when running ERT on a whole file from the command line, it will complain loudly and not even attempt to run any of the tests.

Remove duplicate test function from list-ops-test.el (#225)

---

exercises/practice/hello-world/hello-world.el

Emacs is very unhappy about this complaining about "void-variable (-*-)" for a very valid reason.  I looked through the rest of commit 5031301 and this seems to be the only typo.
I'm going to mention @ErikSchierboom and @fapdash since they where responsible for this change.  Not to be mean, just to let them know.  Everyone makes mistakes :)
Thanks everyone for making this course!  I can't wait to get past the first exercise :P

Fix typo introduced in 5031301

---

.github/configlet-sync-issue.md
.github/workflows/configlet-sync.yml

Found this action on the common-lisp track and it seems very useful to keep a track healthy and up-to-date.
See https://github.com/exercism/common-lisp/blob/de5fadcd239987563f43b67c23863afe485a954d/.github/workflows/configlet-sync.yml
I tested the action on my fork, see
- https://github.com/fapdash/exercism--emacs-lisp/actions/runs/3503328179/jobs/5868317315 (failure is expected since the exercises are currently not in sync)
- https://github.com/fapdash/exercism--emacs-lisp/issues/3

Periodically check if exercises are in sync via GH Action

---

exercises/practice/gigasecond/.meta/tests.toml

Since we are not using a mutable date time type as input we can skip this test.

Sync tests of gigasecond exercise

---

.github/workflows/configlet-sync.yml

The configlet-ci action switched to using the gh cli command and needs to have `GH_TOKEN` set to work now.
This sets the token in the same way as upstream does it at https://github.com/exercism/github-actions/blob/a3f83169a9218d28cae3c04d70522f0519d92d46/.github/workflows/configlet.yml#L29-L33
Previous error was:
> The GH_TOKEN environment variable is not set
See https://github.com/exercism/github-actions/pull/107 for more context

Fix failing configlet-sync GHA workflow

---

exercises/practice/all-your-base/all-your-base-test.el

The exercise from #260 had the `negative-digit` (according to the Python track) test with the duplicate `input-base-is-negative` name.

fix second 'input-base-is-negative' test to be 'negative-digit'

---

exercises/practice/pangram/.meta/example.el
exercises/practice/pangram/pangram-test.el
exercises/practice/pangram/pangram.el

With this PR I'm renaming the function `is-pangram` as `pangramp`. 
Why? Because the latter is more Lispy than the former.
Reference:
* [bbatsov/emacs-lisp-style-guide](https://github.com/bbatsov/emacs-lisp-style-guide)
> The names of predicate methods (methods that return a boolean value) should end in a `p` if it’s a single-word name and a `-p` if it’s a multi-word name (e.g., `evenp` and `buffer-live-p`).
>
> ```elisp
> ;; good
> (defun palindromep ...)
> (defun only-one-p ...)
> 
> ;; bad
> (defun palindrome? ...) ; Scheme style
> (defun is-palindrome ...) ; Java style
> ```

Rename is-pangram function to pangramp

---

.github/workflows/ci.yml

Brings the CI test run in sync with the test runner.
Should be merged in sync with https://github.com/exercism/emacs-lisp-test-runner/pull/58.

Upgrade CI test run to Emacs 28.2

---

README.md

- add missing links
- make alt texts a bit clearer

Link to Discourse and Discord from corresponding badges

---

tools/templates/exercises/practice/test.mustache

- need to use `ert-deftest` for tests instead of `defun`

Fix stub generation for tests in practice exercise generator

---

config.json
exercises/practice/reverse-string/.docs/instructions.md
exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/example.el
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/reverse-string/reverse-string-test.el
exercises/practice/reverse-string/reverse-string.el

The canonical data defines the function to implement as `reverse` but it got changed to `reverse-string` so Emacs users don't overwrite the built in `reverse` function while doing REPL driven programming.

Add reverse-string practice exercise

---

config.json
exercises/practice/flatten-array/.docs/instructions.md
exercises/practice/flatten-array/.meta/config.json
exercises/practice/flatten-array/.meta/example.el
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/flatten-array-test.el
exercises/practice/flatten-array/flatten-array.el

- reverse lists instead of arrays since they are the more common data structure in Emacs Lisp
- use `list-flatten` to make it extra clear that lists are the expected input
- use `list-flatten` instead of `flatten-list` to avoid overwriting built-in Emacs function (alias)

Add flatten-array practice exercise

---

config.json

@exercism/emacs-lisp, this is related to #348, but the example.el file path is incorrect in the track config so new exercises will have it in the wrong location. Then the exercise's config file needs to be updated manually.

Update example.el relative path

---

exercises/practice/roman-numerals/.meta/config.json
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/roman-numerals-test.el
exercises/practice/roman-numerals/roman-numerals.el

Related to #229.
I swapped out `equal` for `string=`, updated the test names, and added the latest test for 3999. I also reformatted the stub to resemble what the exercise generator would make nowadays. Finally, I looked up the original author to give them proper credit.

Sync roman-numerals tests

---

exercises/practice/armstrong-numbers/armstrong-numbers-test.el
exercises/practice/armstrong-numbers/armstrong-numbers.el

Sync armstrong-number tests

---

bin/generate_practice_exercise

@exercism/emacs-lisp, configlet create --practice-exercise <slug> now creates the config entry for the slug as well as sync the problem-specifications metadata / docs. Exercism stopped using floats for the average run time a while ago so that line's not needed either.

Update generator to use configlet create

---

config.json

I grabbed difficulty levels from the Common Lisp track and binned them as 2 (easy) or 5 (medium). Once #348 is merged, that'll format the track config. I'll rebase this PR and then I can move forward with resorting the exercises by difficulty and then name.

Update difficulty levels to sort exercises

---

config.json
exercises/practice/triangle/.docs/instructions.md
exercises/practice/triangle/.meta/config.json
exercises/practice/triangle/.meta/example.el
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/triangle-test.el
exercises/practice/triangle/triangle.el

Function names have a "p" suffix, consistent with naming conventions for predicates.
In all other respects, function and argument names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/triangle/canonical-data.json

feat: Add exercise Triangle (closes #312)

---

config.json
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/collatz-conjecture/.meta/example.el
exercises/practice/collatz-conjecture/.meta/tests.toml
exercises/practice/collatz-conjecture/collatz-conjecture-test.el
exercises/practice/collatz-conjecture/collatz-conjecture.el

Function and argument names, and test cases, are taken from
https://github.com/exercism/problem-specifications/blob/main/exercises/collatz-conjecture/canonical-data.json

feat: Add exercise Collatz Conjecture (closes #310)

---

exercises/practice/gigasecond/.meta/example.el
exercises/practice/gigasecond/gigasecond-test.el
exercises/practice/gigasecond/gigasecond.el

Sync gigasecond tests and stub

---

exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/atbash-cipher/.meta/example.el
exercises/practice/atbash-cipher/atbash-cipher-test.el
exercises/practice/atbash-cipher/atbash-cipher.el

Fix for issue #386. Used the Racket tests as a guide.

fix [Improve Practice Exercise] Atbash Cipher #386

---

bin/test-examples

Executing this script locally required a `git reset` after execution without this change.

`bin/test-examples`: Copy instead of move to make script idempotent

---

tools/practice-exercise-generator.el

practice-exercise-generator: Don't include commas in test names

---

config.json
exercises/practice/variable-length-quantity/.docs/instructions.md
exercises/practice/variable-length-quantity/.meta/config.json
exercises/practice/variable-length-quantity/.meta/example.el
exercises/practice/variable-length-quantity/.meta/tests.toml
exercises/practice/variable-length-quantity/variable-length-quantity-test.el
exercises/practice/variable-length-quantity/variable-length-quantity.el

I went with a difficulty of 6. In Racket it is an 8 which seems a little high. It is a 4 in python.

add variable-length-quantity exercise

---

.github/workflows/configlet-sync.yml

The job sometimes fails because we're hitting a rate limit. Removing `update_existing: true` seems to the main culprit for hitting the rate limit.
See https://github.com/JasonEtco/create-an-issue/issues/142#issuecomment-2066826259
works on #359

Fix flaky configlet-sync job

---

exercises/practice/list-ops/.docs/instructions.append.md

- changes headline level for instructions append to make it show  up in the web UI

list-ops: Make headline for instructions append show up in UI

---

exercises/practice/phone-number/phone-number-test.el

- Revised the following tests using the canonical test data, as suggested by BNAndras.
cleans-number-test
cleans-numbers-with-dots-test
valid-when-11-digits-and-first-is-1-test
- Revised the following tests specific for "Phone Number" to conform the requirements for phone numbers.
area-code-test
pprint-test
pprint-full-us-phone-number-test

Corrected a few tests of "Phone Number" (emacs-lisp  #465)

---

exercises/practice/phone-number/.docs/instructions.append.md

Because the instruction of "Phone Number" had no description about two functions, _area-code_ and _pprint_, which are only required in the Emacs Lisp track, I added their description.

Added a Emacs Lisp track-spepcific instruction to "Phone Number" (#465)

---

exercises/practice/phone-number/.docs/instructions.md

Related to #465, this sync removes mention of user-inputted phone numbers from this exercise.

Sync `phone-number` instructions

---

tools/install-packages.el

- The function exercism//install-required-packages now performs installation only if at least one of thte required applications has not be installed.

Revised tools/install-packages.el (#469)

---

config.json
exercises/practice/phone-number/.meta/config.json
exercises/practice/phone-number/.meta/example.el
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/phone-number/phone-number-test.el
exercises/practice/phone-number/phone-number.el

I have revised the phone-number-test.el to include all problems from the canonical test data and correct the three track-specific problems.

Implemented all "Phone Number" problems from the canonical test data. (#465)

---

exercises/practice/crypto-square/.meta/tests.toml
exercises/practice/crypto-square/crypto-square-test.el
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/meetup/.docs/instructions.md

[no important files changed]
resolves #476

Sync instructions
